theme: jekyll-theme-minimal
title: [Testing and Mointoring ML Pipelines]
description: [My notes and views on testing an ML/AI application]
logo: [/assets/lmn.png]
show_downloads: ["true"]
# google_analytics: [Your Google Analytics tracking ID]